import type {
  KiroAvatarState,
  KiroBehaviorTarget,
  KiroBoneRole,
  KiroMorphRole,
} from './kiro-model.types.ts';

export const KIRO_MODEL_URL = '/models/kiro/kiro.glb';

export const KIRO_BONE_ALIASES: Record<KiroBoneRole, readonly string[]> = {
  head: ['head', 'mixamorighead', 'ccbasehead', 'jhead'],
  neck: ['neck', 'mixamorigneck', 'ccbaseneck', 'jneck'],
  spine: ['spine2', 'spine1', 'spine', 'chest', 'upperchest', 'mixamorigspine2'],
  leftEye: ['lefteye', 'eyeleft', 'eyel', 'jeyel', 'mixamoriglefteye'],
  rightEye: ['righteye', 'eyeright', 'eyer', 'jeyer', 'mixamorigrighteye'],
  leftUpperArm: ['leftarm', 'upperarmleft', 'upperarml', 'mixamorigleftarm'],
  leftForearm: ['leftforearm', 'forearmleft', 'lowerarml', 'mixamorigleftforearm'],
  rightUpperArm: ['rightarm', 'upperarmright', 'upperarmr', 'mixamorigrightarm'],
  rightForearm: ['rightforearm', 'forearmright', 'lowerarmr', 'mixamorigrightforearm'],
  leftUpperLeg: ['leftupleg', 'leftthigh', 'upperlegleft', 'mixamorigleftupleg'],
  leftLowerLeg: ['leftleg', 'leftcalf', 'lowerlegleft', 'mixamorigleftleg'],
  rightUpperLeg: ['rightupleg', 'rightthigh', 'upperlegright', 'mixamorigrightupleg'],
  rightLowerLeg: ['rightleg', 'rightcalf', 'lowerlegright', 'mixamorigrightleg'],
  board: ['hoverboard', 'board', 'kiroboard', 'flyingboard'],
  leftThruster: ['leftthruster', 'thrusterleft', 'engineleft', 'jetleft', 'thrusterl'],
  rightThruster: ['rightthruster', 'thrusterright', 'engineright', 'jetright', 'thrusterr'],
};

export const KIRO_MORPH_ALIASES: Record<KiroMorphRole, readonly string[]> = {
  blinkLeft: ['blinkleft', 'eyeblinkleft', 'blinkl', 'eyeclosedleft'],
  blinkRight: ['blinkright', 'eyeblinkright', 'blinkr', 'eyeclosedright'],
  smile: ['smile', 'mouthsmile', 'happy', 'mouthhappy'],
  mouthOpen: ['mouthopen', 'jawopen', 'openmouth', 'visemeaa', 'aa'],
  browUpLeft: ['browupleft', 'eyebrowupleft', 'browraisel', 'browouterupleft'],
  browUpRight: ['browupright', 'eyebrowupright', 'browraiser', 'browouterupright'],
};

export const KIRO_STATE_CLIP_KEYWORDS: Record<KiroAvatarState, readonly string[]> = {
  idle: ['idle', 'hover', 'breath', 'stand'],
  thinking: ['think', 'thinking', 'ponder', 'curious'],
  retrieving: ['retrieve', 'retrieving', 'search', 'scan', 'fly', 'forward'],
  answering: ['answer', 'answering', 'talk', 'talking', 'speak', 'speaking'],
  success: ['success', 'celebrate', 'celebration', 'happy', 'victory'],
  error: ['error', 'confused', 'fail', 'failure', 'frustrated'],
};

export const KIRO_STATE_TARGETS: Record<KiroAvatarState, KiroBehaviorTarget> = {
  idle: {
    headYaw: 0,
    headPitch: 0,
    headRoll: 0,
    gazeX: 0,
    gazeY: 0,
    smile: 0.08,
    mouthOpen: 0,
    blinkLeft: 0,
    blinkRight: 0,
    browLiftLeft: 0,
    browLiftRight: 0,
    bodyLean: 0,
    boardPitch: 0,
    boardRoll: 0,
    leftThrust: 0.38,
    rightThrust: 0.38,
    hoverAmount: 0.16,
  },
  thinking: {
    headYaw: 0.12,
    headPitch: -0.04,
    headRoll: -0.08,
    gazeX: 0.42,
    gazeY: 0.22,
    smile: 0.02,
    mouthOpen: 0,
    blinkLeft: 0,
    blinkRight: 0,
    browLiftLeft: 0.08,
    browLiftRight: 0.18,
    bodyLean: 0,
    boardPitch: 0,
    boardRoll: -0.02,
    leftThrust: 0.4,
    rightThrust: 0.4,
    hoverAmount: 0.12,
  },
  retrieving: {
    headYaw: 0,
    headPitch: 0.05,
    headRoll: 0,
    gazeX: 0,
    gazeY: -0.03,
    smile: 0,
    mouthOpen: 0,
    blinkLeft: 0,
    blinkRight: 0,
    browLiftLeft: -0.04,
    browLiftRight: -0.04,
    bodyLean: 0.08,
    boardPitch: -0.08,
    boardRoll: 0,
    leftThrust: 0.76,
    rightThrust: 0.76,
    hoverAmount: 0.08,
  },
  answering: {
    headYaw: -0.04,
    headPitch: 0,
    headRoll: 0,
    gazeX: 0.08,
    gazeY: 0,
    smile: 0.18,
    mouthOpen: 0.12,
    blinkLeft: 0,
    blinkRight: 0,
    browLiftLeft: 0.04,
    browLiftRight: 0.04,
    bodyLean: 0.02,
    boardPitch: 0,
    boardRoll: 0,
    leftThrust: 0.48,
    rightThrust: 0.48,
    hoverAmount: 0.12,
  },
  success: {
    headYaw: 0,
    headPitch: -0.03,
    headRoll: -0.03,
    gazeX: 0,
    gazeY: 0,
    smile: 0.62,
    mouthOpen: 0.05,
    blinkLeft: 0,
    blinkRight: 0,
    browLiftLeft: 0.12,
    browLiftRight: 0.12,
    bodyLean: 0,
    boardPitch: 0.02,
    boardRoll: 0,
    leftThrust: 0.58,
    rightThrust: 0.58,
    hoverAmount: 0.18,
  },
  error: {
    headYaw: -0.06,
    headPitch: 0.06,
    headRoll: 0.08,
    gazeX: -0.14,
    gazeY: -0.08,
    smile: -0.18,
    mouthOpen: 0.02,
    blinkLeft: 0,
    blinkRight: 0,
    browLiftLeft: -0.06,
    browLiftRight: 0.04,
    bodyLean: -0.02,
    boardPitch: 0,
    boardRoll: 0.02,
    leftThrust: 0.32,
    rightThrust: 0.36,
    hoverAmount: 0.08,
  },
};

export const KIRO_LIMITS = {
  headYawRadians: 0.34,
  headPitchRadians: 0.26,
  headRollRadians: 0.2,
  eyeYawRadians: 0.22,
  eyePitchRadians: 0.16,
  bodyLeanRadians: 0.08,
  boardPitchRadians: 0.14,
  boardRollRadians: 0.12,
  thrusterScaleMin: 0.96,
  thrusterScaleMax: 1.12,
  hoverDistanceRatio: 0.008,
} as const;
